
DELETE http://localhost:3001/api/persons/<id>

###
#non existent
DELETE http://localhost:3001/api/persons/637b7d347df8d6066cbf6c26

###
#malformat id
DELETE http://localhost:3001/api/persons/1
###

GET http://localhost:3001/api/persons