POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sherlock6test",
    "number": "000-111111"
}

###
# Update Person

@id = 637d9eef606cdc9a546b3dcc

PUT http://localhost:3001/api/persons/{{id}}
Content-Type: application/json

{
    "name": "test",
    "number": "12-32567891"
}