POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sherlock Holmes",
    "number": "12-32-4216534"
}

###
# Update Person

@id = 637c8756f25fe1bdf9dbe082

PUT http://localhost:3001/api/persons/{{id}}
Content-Type: application/json

{
    "name": "Sherlock Holmes",
    "number": "12-34-567891"
}